# Read about factories at https://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  factory :survey_definition do
    definition %Q({
      "出生地(Place of birth)" : [
        "北京市(Beijing)",
        "天津市(Tianjing)",
        "上海市(Shanghai)",
        "重庆市(Chongqing)",
        "安徽省(Anhui)",
        "福建省(Fujian)",
        "甘肃省(Gansu)",
        "广东省(Guangdong)",
        "贵州省(Guizhou)",
        "河北省(Hebei)",
        "黑龙江省(Heilongjiang)",
        "河南省(Henan)",
        "湖北省(Hubei)",
        "湖南省(Hunan)",
        "吉林省(Jilin)",
        "江西省(Jiangxi)",
        "江苏省(Jiangsu)",
        "辽宁省(Liaoning)",
        "山东省(Shandong)",
        "陕西省(Shaanxi)",
        "山西省(Shanxi)",
        "四川省(Sichuan)",
        "云南省(Yunnan)",
        "浙江省(Zhejiang)",
        "青海省(Qinghai)",
        "海南省(Hainan)",
        "广西(Guangxi)",
        "内蒙古(Neimenggu)",
        "宁夏(Ningxia)",
        "西藏(Xizang)",
        "新疆(Xinjiang)",
        "香港(Xianggang)",
        "澳门(Aomen)",
        "台湾(Taiwan)"
      ],
      "检查认真彻底(Thorough examination)" : [
        "急待改进(Not satisfied)",
        "待改进(Not very satisfied)",
        "一般(Average)",
        "较好(Quite satisfied)",
        "非常好(Very satisifed)"
      ],
      "解释清楚准确(Explains clearly)" : [
        "急待改进(Not satisfied)",
        "待改进(Not very satisfied)",
        "一般(Average)",
        "较好(Quite satisfied)",
        "非常好(Very satisifed)"
      ],
      "体重(Weight)" : [
        "30KG",
        "31KG",
        "32KG",
        "33KG",
        "34KG",
        "35KG",
        "36KG",
        "37KG",
        "38KG",
        "39KG",
        "40KG",
        "41KG",
        "42KG",
        "43KG",
        "44KG",
        "45KG",
        "46KG",
        "47KG",
        "48KG",
        "49KG",
        "50KG",
        "51KG",
        "52KG",
        "53KG",
        "54KG",
        "55KG",
        "56KG",
        "57KG",
        "58KG",
        "59KG",
        "60KG",
        "61KG",
        "62KG",
        "63KG",
        "64KG",
        "65KG",
        "66KG",
        "67KG",
        "68KG",
        "69KG",
        "70KG",
        "71KG",
        "72KG",
        "73KG",
        "74KG",
        "75KG",
        "76KG",
        "77KG",
        "78KG",
        "79KG",
        "80KG",
        "81KG",
        "82KG",
        "83KG",
        "84KG",
        "85KG",
        "86KG",
        "87KG",
        "88KG",
        "89KG",
        "90KG",
        "91KG",
        "92KG",
        "93KG",
        "94KG",
        "95KG",
        "96KG",
        "97KG",
        "98KG",
        "99KG",
        "100KG",
        "101KG",
        "102KG",
        "103KG",
        "104KG",
        "105KG",
        "106KG",
        "107KG",
        "108KG",
        "109KG",
        "110KG",
        "111KG",
        "112KG",
        "113KG",
        "114KG",
        "115KG",
        "116KG",
        "117KG",
        "118KG",
        "119KG",
        "120KG",
        "121KG",
        "122KG",
        "123KG",
        "124KG",
        "125KG",
        "126KG",
        "127KG",
        "128KG",
        "129KG",
        "130KG",
        "131KG",
        "132KG",
        "133KG",
        "134KG",
        "135KG",
        "136KG",
        "137KG",
        "138KG",
        "139KG",
        "140KG",
        "141KG",
        "142KG",
        "143KG",
        "144KG",
        "145KG",
        "146KG",
        "147KG",
        "148KG",
        "149KG",
        "150KG",
        "151KG",
        "152KG",
        "153KG",
        "154KG",
        "155KG",
        "156KG",
        "157KG",
        "158KG",
        "159KG",
        "160KG"
      ],
      "生日(Date of birth)" : "input#dob",
      "卫生情况(Cleanliness)" : [
        "急待改进(Not satisfied)",
        "待改进(Not very satisfied)",
        "一般(Average)",
        "较好(Quite satisfied)",
        "非常好(Very satisifed)"
      ],
      "等待时间(Waiting time)" : [
        "无需等待(No waiting)",
        "5分钟(5min)",
        "10分钟(10min)",
        "15分钟(15min)",
        "30分钟(30min)",
        "45分钟(45min)",
        "1小时(1hr)",
        "1小时15分钟(1hr 15min)",
        "1小时30分钟(1hr 30min)",
        "1小时45分钟(1hr 45min)",
        "2小时(2hr)",
        "2小时30分钟(2hr 30min)",
        "3小时(3hr)",
        "3小时30分钟(3hr 30min)",
        "4小时或更多(4hr)"
      ],
      "职业(Occupation)" : [
        "专业人员(Professionals)",
        "高级行政管理（董事长\/总经理\/行政总裁）(Managing Director \/ Chief Executive Officer)",
        "经理(Manager)",
        "老板\/合伙人\/自雇(Owner \/ partner \/ self-employed)",
        "白领(White collar)",
        "政府人员\/机关干部(Government officials \/ cadres)",
        "蓝领(Blue Collar)",
        "技术人员(Technical staff)",
        "家庭主妇(Housewife)",
        "退休(Retirement)",
        "学生(Student)",
        "失业\/待业(Unemployed)",
        "自由职业者(Freelance)",
        "其它（请注明）(Other (please specify))"
      ],
      "听取患者叙述(Listens patiently)" : [
        "急待改进(Not satisfied)",
        "待改进(Not very satisfied)",
        "一般(Average)",
        "较好(Quite satisfied)",
        "非常好(Very satisifed)"
      ],
      "设施齐全(Facilities)" : [
        "急待改进(Not satisfied)",
        "待改进(Not very satisfied)",
        "一般(Average)",
        "较好(Quite satisfied)",
        "非常好(Very satisifed)"
      ],
      "提供必要诊疗(Accurate diagnosis)" : [
        "急待改进(Not satisfied)",
        "待改进(Not very satisfied)",
        "一般(Average)",
        "较好(Quite satisfied)",
        "非常好(Very satisifed)"
      ],
      "教育水平(Education)" : [
        "高中(Senior middle school)",
        "大专(College)",
        "大学本科(Undergraduate)",
        "硕士(Master's degree)",
        "博士(Doctor)",
        "其它（请注明）(Other (please specify))"
      ],
      "电话(Mobile)" : "input#phone",
      "医生点评(Physician assessment)" : [
        "Physician 97\/Speciality 77",
        "Physician 98\/Speciality 8",
        "Physician 362\/Speciality 84",
        "Physician 100\/Speciality 84",
        "Physician 101\/Speciality 84",
        "Physician 104\/Speciality 37",
        "Physician 106\/Speciality 57",
        "Physician 109\/Speciality 36",
        "Physician 110\/Speciality 68",
        "Physician 108\/Speciality 36",
        "Physician 102\/Speciality 48",
        "Physician 105\/Speciality 23",
        "Physician 103\/Speciality 84",
        "Physician 107\/Speciality 36",
        "Physician 353\/Speciality 97",
        "Physician 142\/Speciality 63",
        "Physician 143\/Speciality 36",
        "Physician 200\/Speciality 72",
        "Physician 229\/Speciality 72",
        "Physician 201\/Speciality 101",
        "Physician 387\/Speciality 99",
        "Physician 243\/Speciality 23",
        "Physician 244\/Speciality 99",
        "Physician 255\/Speciality 19",
        "Physician 266\/Speciality 99",
        "Physician 267\/Speciality 68",
        "Physician 268\/Speciality 44",
        "Physician 270\/Speciality 19",
        "Physician 271\/Speciality 44",
        "Physician 274\/Speciality 122",
        "Physician 273\/Speciality 19",
        "Physician 377\/Speciality 72",
        "Physician 232\/Speciality 72",
        "Physician 269\/Speciality 117",
        "Physician 265\/Speciality 99",
        "Physician 380\/Speciality 68",
        "Physician 297\/Speciality 70",
        "Physician 304\/Speciality 68",
        "Physician 322\/Speciality 84",
        "Physician 390\/Speciality 97",
        "Physician 291\/Speciality 126"
      ],
      "邮箱(Email)" : "input#email",
      "性别(Gender)" : [
        "男(Male)",
        "女(Female)"
      ],
      "身高(Height)" : [
        "120CM",
        "121CM",
        "122CM",
        "123CM",
        "124CM",
        "125CM",
        "126CM",
        "127CM",
        "128CM",
        "129CM",
        "130CM",
        "131CM",
        "132CM",
        "133CM",
        "134CM",
        "135CM",
        "136CM",
        "137CM",
        "138CM",
        "139CM",
        "140CM",
        "141CM",
        "142CM",
        "143CM",
        "144CM",
        "145CM",
        "146CM",
        "147CM",
        "148CM",
        "149CM",
        "150CM",
        "151CM",
        "152CM",
        "153CM",
        "154CM",
        "155CM",
        "156CM",
        "157CM",
        "158CM",
        "159CM",
        "160CM",
        "161CM",
        "162CM",
        "163CM",
        "164CM",
        "165CM",
        "166CM",
        "167CM",
        "168CM",
        "169CM",
        "170CM",
        "171CM",
        "172CM",
        "173CM",
        "174CM",
        "175CM",
        "176CM",
        "177CM",
        "178CM",
        "179CM",
        "180CM",
        "181CM",
        "182CM",
        "183CM",
        "184CM",
        "185CM",
        "186CM",
        "187CM",
        "188CM",
        "189CM",
        "190CM",
        "191CM",
        "192CM",
        "193CM",
        "194CM",
        "195CM",
        "196CM",
        "197CM",
        "198CM",
        "199CM",
        "200CM",
        "201CM",
        "202CM",
        "203CM",
        "204CM",
        "205CM",
        "206CM",
        "207CM",
        "208CM",
        "209CM",
        "210CM",
        "211CM",
        "212CM",
        "213CM",
        "214CM",
        "215CM",
        "216CM",
        "217CM",
        "218CM",
        "219CM",
        "220CM"
      ],
      "其他国家(Other country)" : "input",
      "治疗效果明显(Treatment success)" : [
        "急待改进(Not satisfied)",
        "待改进(Not very satisfied)",
        "一般(Average)",
        "较好(Quite satisfied)",
        "非常好(Very satisifed)"
      ],
      "对医生的补充意见(Additional comments about physician)" : "textarea",
      "我同意由CareVoice及其合作伙伴联络我(By checking this box, I agree to be reached by The CareVoice partners.)" : "checkbox",
      "对医院的补充意见(Additional comments about hospital)" : "textarea",
      "收入水平\/CNY(Family monthly income \/ CNY)" : [
        "5000 以下(Below 5000)",
        "5000 至 10000(5000-10000)",
        "10000 至 20000(10000-20000)",
        "20000 至 35000(20000-35000)",
        "35000 至 50000(35000-50000)",
        "50000 以上(50,000 or more)"
      ],
      "预约服务(Appointment making service)" : [
        "急待改进(Not satisfied)",
        "待改进(Not very satisfied)",
        "一般(Average)",
        "较好(Quite satisfied)",
        "非常好(Very satisifed)"
      ]
    })
    survey_type 'B2B2C'
  end
end
