# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'OAuth2Test' do
pod 'AFOAuth2Manager'
pod 'AFNetworking'
pod 'ReactiveCocoa', '4.0.4-alpha-4'

end

