puts "Create conditions "

{
  'Common diseases of respiratory system' => ["Acute Silicosis", "Adult Respiratory Distress Syndrome", "Asbestosis", "Aspiration Pneumonia", "Asthma", "Asthma-Adult", "Asthma-Child", "Atelectasis", "Berylliosis", "Bronchitis", "Bronchopulmonary Dysplasia", "Chronic Bronchitis", "Chronic Obstructive Pulmonary Disease", "Cough", "Drowning", "Emphysema", "Hiccups", "Idiopathic Pulmonary Fibrosis", "Laryngitis", "Lung Cancer", "Osteogenesis Imperfecta", "Pharyngitis/Tonsillopharyngitis", "Pleural Effusion", "Pleurisy", "Pneumonia", "Pneumothorax", "Pulmonary Embolism", "Pulmonary Hypertension", "Respiratory Distress Syndrome In Newborns", "Sarcoidosis", "Severe Acute Respiratory Syndrome", "Sinusitis", "Sleep Apnea", "Snoring", "Sudden Infant Death Syndrome", "Transient Tachypnea Of Newborn", "Wegener's Granulomatosis"],
  'Common diseases of the circulatory system(cardiovascular system)' => ["Acute coronary syndromes", "Angina", "Arrhythmia", "Congenital heart disease", "Coronary heart disease", "Heart failure", "Inflammatory heart disease", "Ischaemic heart disease", "Rheumatic heart disease", "Valvular disease", "Cerebrovascular disease (stroke)", "Haemorrhagic stroke", "Ischaemic stroke", "Deep vein thrombosis", "Hypertensive heart disease", "Peripheral artery disease (PAD)", "Pulmonary embolism", "Aortic Insufficiency", "Aortic Regurgitation", "Aortic Stenosis", "Atrial Fibrillation", "Atrial Flutter", "Atrial Septal Defect", "Atrioventricular Septal Defect", "Bradycardia", "Cardiac Arrest", "Cardiac Tamponade", "Cardiomyopathy", "Congestive Heart Failure", "Coronary Artery Disease CAD", "Endocarditis", "Heart Block", "Heart Murmur", "Hypertrophic Cardiomyopathy", "Mitral Regurgitation", "Mitral Stenosis", "Mitral Valve Prolapse", "Myocarditis", "Paroxysmal Supraventricular Tachycardia", "Patent Ductus Arteriosus", "Pericarditis", "Premature Ventricular Beats", "Prosthetic Heart Valve Thrombosis", "Septal Defects", "Sick Sinus Syndrome", "Tachycardia", "Tetralogy Of Fallot", "Tricuspid Valve Disease", "Ventricular Fibrillation", "Ventricular Septal Defect", "Ventricular Tachycardia", "Wolff-Parkinson-White Syndrome"],
  'Common diseases of the digestive/ GIT system' => ["Achalasia", "Acute Abdomen", "Barrett's Esophagus", "Celiac Disease", "Cirrhosis", "Colic", "Constipation", "Diarrhea", "Dysphagia", "Esophageal Cancer", "Esophageal Stricture", "Gallstones", "Heartburn", "Irritable Bowel Syndrome IBS", "Leukoplakia", "Peptic Ulcer", "Ulcerative Colitis", "Abdominal Hernia", "Anal Abscess (and Anal Fistula)", "Anal Atresia", "Anal Cancer", "Anal Fissure", "Angiodysplasia Of The Colon", "Appendicitis", "Ascites", "Celiac Disease", "Chronic Pancreatitis", "Colon Cancer", "Colon Polyps", "Crohn's Disease", "Diverticulitis", "Duodenal Ulcer", "Dyspepsia", "Encopresis", "Enterocutaneous Fistula", "Esophageal Varices", "Familial Adenomatous Polyposis", "Fecal Incontinence", "Fever Of Unknown Origin", "Folic Acid Deficiency", "Gallstones", "Gastric Ulcer", "Gastritis", "Gastroesophageal Reflux Disease In Children With Disabilities", "Gastroesophageal Reflux Disease-Adolescent", "Gastroesophageal Reflux Disease-Child", "Gastroesophageal Reflux Disease-Infant", "Groin Hernia", "Heartburn-Overview", "Hemorrhoids", "Hiatal Hernia", "Hirschsprung's Disease", "Ileus", "Inflammatory Bowel Disease", "Intestinal Pseudo-obstruction", "Intussusception", "Irritable Bowel Syndrome", "Ischemic Bowel Disease", "Lactose Intolerance", "Malabsorption", "Mechanical Bowel Obstruction", "Meckel's Diverticulum", "Menkes Syndrome", "Necrotizing Enterocolitis", "Pancreatic Cancer", "Peptic Ulcer", "Peritonitis", "Primary Biliary Cirrhosis", "Pruritus Ani", "Pyloric Stenosis", "Rectal Prolapse", "Short Bowel Syndrome", "Small Bowel Obstruction", "Stomach Cancer", "Ulcerative Colitis", "Whipple's Disease", "Wilson's Disease", "Zollinger-Ellison Syndrome"],
  'Common diseases of the urinary system' => ["Acute Cystitis", "Bed-wetting", "Benign Prostatic Hyperplasia", "Benign Prostatic Hyperplasia BPH", "Bladder Cancer", "Hematuria", "Hydronephrosis", "Interstitial Cystitis", "Urinary Incontinence", "Urinary Incontinence-Female", "Vesicoureteral Reflux"],
  'Common diseases of the blood system' => ["Agranulocytosis", "Amyloidosis", "Anemia", "Anemia Of Chronic Disease", "Aplastic Anemia", "Autoimmune Hemolytic Anemia", "Chronic Lymphocytic Leukemia", "Chronic Myelocytic Leukemia", "Disseminated Intravascular Coagulation", "Hemochromatosis", "Hemophilia", "Heparin-Induced Thrombocytopenia", "Idiopathic Thrombocytopenic Purpura", "Iron-Deficiency Anemia", "Leukemia", "Multiple Myeloma", "Myelodysplastic Syndromes", "Primary Polycythemia", "Rh Incompatibility and Isoimmunization", "Sickle Cell Disease", "Spherocytosis", "Thalassemia", "Von Willebrand Disease"],
  'Common diseases of the endocrine system' => ["Acromegaly", "Addison's Disease", "Adrenal Crisis", "Apoplexy", "Cushing's Syndrome", "Diabetes Insipidus", "Gestational Diabetes", "Hyperosmolar Nonketotic Coma", "Hyperparathyroidism", "Hyperthyroidism", "Hypoparathyroidism", "Hypopituitarism", "Hypothyroidism", "Metabolic Syndrome NEW", "Nontoxic Nodular Goiter", "Osteoporosis", "Panhypopituitarism", "Thyroid Cancer", "Type 1 Diabetes", "Type 2 Diabetes"],
  'Common diseases of the nervous system' => ["Acute Cerebellar Ataxia", "Alexic Anomia", "Alzheimer's Disease", "Amyotrophic Lateral Sclerosis", "Anoxic Brain Damage", "Aphasia-associated Anomia", "Arnold-Chiari Syndrome", "Aseptic Meningitis", "Auditory Neuropathy", "Bell's Palsy", "Benign Essential Tremor", "Benign Paroxysmal Positional Vertigo", "Carpal Tunnel Syndrome", "Central Cord Syndrome", "Cervical Myelopathy", "Charcot-Marie-Tooth Disease", "Chronic Fatigue Syndrome CFS", "Cluster Headache", "Coma", "Complex Regional Pain Syndrome", "Concussion", "Contusion", "Creutzfeldt-Jakob Disease", "Dandy-Walker Syndrome", "Delirium", "Delirium Tremens", "Dementia", "Diabetic Neuropathy", "Duchenne Muscular Dystrophy", "Epilepsy", "Febrile Seizures", "Focal Dystonia", "Friedreich's Ataxia", "Guillain-Barré Syndrome", "Hearing Loss", "Hemifacial Spasm", "Huntington's Disease", "Hydrocephalus", "Hypoxic Ischemic Encephalopathy", "Korsakoff's Syndrome", "Lewy Body Disease", "Migraine", "Mild Cognitive Impairment", "Multiple Sclerosis", "Multiple Sclerosis MS", "Multiple System Atrophy", "Muscle Strain", "Muscular Dystrophy", "Myoclonus", "Paraplegia", "Parkinson's Disease", "Periodic Paralysis Syndrome", "Peripheral Neuropathy", "Phantom Limb Syndrome", "Post-polio Syndrome", "Quadriplegia and Paraplegia", "Restless Legs Syndrome", "Sciatica", "Seizure Disorder", "Seizure-Child", "Shaken Baby Syndrome", "Shingles", "Shy-Drager Syndrome", "Sinus Headache", "Sleep Apnea", "Stroke", "Stuttering", "Subacute Sclerosing Panencephalitis", "Subarachnoid Hemorrhage", "Subdural Hematoma", "Tardive Dyskinesia", "Tarlov Cyst", "Temporomandibular Disorder", "Tension Headache", "Transient Ischemic Attack", "Trigeminal Neuralgia", "Vascular Dementia"],
  'Common diseases of the locomotor system' => ["congenital malformation", "fracture", "chronic soft tissue injury", "Chronic damage of bone", "Chronic injury of cartilage", "intervertebral disk hernia", "cervical syndrome", "medullitis", "arthritis", "tuberculosis of bone and joint", "bone tumor"],
  'Common diseases of metabolism and nutrition' => ["Heterotopic Ossification", "Hyperlipidemia", "Hypoglycemia", "Hypothermia", "Hypothyroidism", "Lipid Disorders", "Metabolic Syndrome", "Nutritional Anemia", "Obesity", "Pseudogout", "Rickets and Osteomalacia", "Scurvy", "Vitamin B12 Deficiency", "Vitamin D Deficiency"],
  'Common rheumatic diseases' => ["rheumatoid arthritis", "SLE; systemic lupus erythematosus", "ankylosing spondylitis", "sicca syndrome", "vasculitides", "idiopathic inflammatory myopathies", "systemic sclerosis", "Raynaud disease", "osteoarthritis", "fibromyalgia syndrome"],
  'Dental & Oral Diseases' => ["Acute Necrotizing Ulcerative Gingivitis", "Bruxism", "Gingivitis", "Impacted Tooth", "Periodontal Disease", "Teething", "Tooth Abscess", "Tooth Decay"],
  'Eye Diseases' => ["Adult Macular Degeneration", "Amblyopia", "Angle-Closure Glaucoma", "Astigmatism", "Blepharitis", "Cataract", "Chalazion", "Chorioretinitis", "Color Blindness", "Conjunctivitis", "Corneal Abrasion", "Corneal Opacity", "Dacryocystitis", "Detached Retina", "Eye Contusion", "Farsightedness", "Glaucoma", "Hordeolum", "Keratoconjunctivitis Sicca", "Macular Degeneration", "Middle Ear Infection", "Nearsightedness and Farsightedness", "Newborn Conjunctivitis", "Newborn Jaundice", "Night Blindness", "Nystagmus", "Open-Angle Glaucoma", "Optic Neuritis", "Orbital Cellulitis", "Presbyopia", "Pterygium", "Retinitis Pigmentosa", "Retinoblastoma", "Strabismus", "Uveitis"],
  'Ear Diseases' => ["Barotrauma", "Cerumen Impaction", "Cholesteatoma", "Deafness", "Eustachian Tube Dysfunction", "Hearing Loss", "Labyrinthitis", "Meniere's Disease", "Motion Sickness", "Otitis Externa", "Otitis Media", "Otosclerosis", "Presbycusis", "Ruptured Eardrum", "Tinnitus", "Vertigo"],
  'Common diseases of Reproductive system' => ["Amenorrhea", "Atrophic Vaginitis", "Cervical Cancer", "Delayed Sexual Development", "Dysmenorrhea", "Dyspareunia", "Endometriosis", "Epididymitis", "Female Sexual Dysfunction", "Hydrocele/Varicocele", "Impotence", "Infertility In Men", "Infertility In Women", "Male Infertility", "Mastalgia", "Mastitis", "Ovarian Cancer", "Ovarian Cyst", "Premature Birth", "Premature Ejaculation", "Premenstrual Syndrome", "Prostate Cancer", "Prostatitis", "Testicular Cancer", "Uterine Cancer", "Uterine Fibroids", "Vaginal Yeast Infection", "Vaginismus"],
  'Common gynecological diseases' => ["Chronic Pelvic Pain", "Cystocele/Rectocele", "Endometriosis", "Heavy Menstrual Bleeding", "Menopause", "Menstrual Disorders", "Polycystic Ovary Syndrome", "Premenstrual Syndrome PMS", "Rectovaginal Fistula", "Urethral Syndrome", "Uterine Fibroids", "Uterine Prolapse", "Vaginal Prolapse", "Vulvodynia"],
  'Common dermatological diseases' => ["Acanthosis Nigricans", "Acne", "Acrochordons", "Actinic Keratosis", "Albinism", "Alopecia", "Animal Bites", "Aphthous Ulcers", "Basal Cell Carcinoma", "Behcet's Disease", "Blisters", "Boil", "Burner Or Stinger", "Burns", "Calluses and Corns", "Cellulitis", "Diaper Rash", "Eczema", "Electrical Burns", "Epidermal Cyst", "Erythema Multiforme", "Erythema Nodosum", "Frostbite", "Hemangioma", "Hidradenitis Suppurativa", "Hirsutism", "Hives", "Hyperhidrosis", "Ichthyosis", "Impetigo", "Ingrown Toenail", "Keloid", "Lichen Planus", "Melanoma", "Moles", "Onychomycosis", "Paronychia", "Pemphigus", "Pilonidal Cyst", "Pityriasis Rosea", "Poison Ivy, Poison Oak, Poison Sumac", "Port-Wine Stains", "Pressure Sores", "Psoriasis", "Pyoderma Gangrenosum", "Rosacea", "Scleroderma", "Seborrheic Dermatitis", "Seborrheic Keratosis", "Squamous Cell Carcinoma", "Sunburn", "Systemic Lupus Erythematosus", "Tinea Versicolor", "Vitiligo", "Wound Dehiscence", "Xanthelasma and Xanthoma"],
  'Common diseases in pregnant women' => ["Ectopic Pregnancy", "Gestational Diabetes", "Hyperemesis Gravidarum", "Macrosomia", "Miscarriage", "Placenta Previa", "Placental Abruption", "Postpartum Hemorrhage", "Pre-eclampsia", "Precocious Sexual Development", "Premature Rupture Of Membranes", "Shoulder Dystocia", "Threatened Abortion", "Umbilical Cord Prolapse", "Vaginal Tears"],
  'Common pediatric diseases' => ["Nutrition disorders", "neonatal asphyxia", "hypoxie-ischemic encephalopathy", "intracranial hemorrhage of newborn", "Meconium aspiration syndrome", "respiratory distress syndrome", "neonatal jaundice", "hemolytic disease of newborn", "Infectious disease of the newborn", "neonatal cold injury syndrome", "necrotizing enterocolitis of newborn", "neonatal hemorrhagic disease", "Neonatal hypoglycemia and hyperglycemia", "neonatal hypocalcemia", "Neonatal umbilical diseases", "Neonatal injury disease", "Down's syndrome", "phenylketonuria", "Wilson disease", "immunologic deficiency disease", "rheumatic fever", "Kawasaki’s disease", "measles", "poliomyelitis", "crystalli", "epidemic parotitis", "congenital hypertrophic pyloric stenosis", "intussusception", "congenital megacolon", "dysentery", "Infantile hepatitis syndrome", "respiratory infection", "congenital heart disease", "glomerulonephritis", "nephrotic syndrome", "nutritional anemia", "epilepsia", "convulsions", "purulent meningitis", "viral meningitis", "myasthenia gravis", "cerebral palsy", "progressive muscular dystrophy", "precocious puberty", "growth hormone deficiency", "child diabetes"],
  'Common infectious disease' => ["Actinomycosis", "Adenovirus Infection", "AIDS", "Allergic Bronchopulmonary Aspergillosis (ABPA)", "Amoebic Dysentery", "Anthrax", "Antibiotic-associated Colitis-C Difficile", "Ascariasis", "Aspergillosis", "Athlete's Foot", "Atypical Pneumonia (Mycoplasma and Viral)", "Avian Influenza", "Bacterial Endocarditis", "Bacterial Meningitis", "Bacterial Vaginosis", "Botulinum Toxin", "Botulism", "Bronchiolitis", "Brucellosis", "Cat Scratch Fever", "Chickenpox", "Chlamydia", "Cholera", "CMV Infection", "Coccidioidomycosis", "Cold Sores", "Colorado Tick Fever", "Common Cold", "Congenital Syphilis", "Croup", "Cryptosporidiosis", "Dengue Fever", "Diabetic Foot Ulcer", "Diphtheria", "Eastern Equine Encephalitis", "Ebola Hemorrhagic Fever", "Encephalitis", "Epiglottitis", "Erythema Infectiosum", "Gangrene", "Genital Herpes", "Genital Warts", "Giardiasis", "Group B Streptococcal Disease", "Hand, Foot, and Mouth Disease", "Hantavirus Infection", "Herpes Simplex 1", "Histoplasmosis", "HIV and AIDS", "Japanese Encephalitis", "Jock Itch", "Legionnaire's Disease", "Leptospirosis", "Lyme Disease", "Malaria", "Measles", "Methicillin-Resistant Staph Infection", "Molluscum Contagiosum", "Mononucleosis", "Mosquito-Borne Viral Encephalitis", "Mucormycosis", "Mumps", "Neonatal Sepsis", "Noroviruses", "Osteomyelitis", "Pancreatitis", "Pandemic (H1N1) 2009 Influenza", "Parotitis", "Peritonsillar Abscess", "Pinworm", "Plague", "Plantar Warts", "Pneumocystis Pneumonia", "Pneumonia", "Poliomyelitis", "Psittacosis", "Rabies", "Respiratory Syncytial Virus", "Rheumatic Fever", "Ringworm", "Rocky Mountain Spotted Fever", "Roseola", "Rotavirus", "Rubella", "Salmonellosis", "Scarlet Fever", "Seasonal Influenza", "Septic Arthritis", "Septic Shock", "Shingles", "Smallpox", "St. Louis Encephalitis", "Strep Throat", "Syphilis", "Tapeworm", "Tetanus", "Thrush", "Tinea Capitis", "Tinea Nigra", "Toxic Shock Syndrome", "Toxoplasmosis", "Traveler's Diarrhea", "Tuberculosis", "Tularemia", "Typhoid Fever", "Urethritis", "Urinary Tract Infection", "Urinary Tract Infection UTI", "Urinary Tract Infections In Childhood", "Vancomycin-Resistant Enterococci Infection", "Viral Gastroenteritis", "Viral Meningitis", "Viral Pharyngitis", "Viral Upper Respiratory Tract Infections", "West Nile Virus", "Western Equine Encephalitis", "Whooping Cough", "Yellow Fever"],
  'Common psychological （mental） diseases' => ["schizophrenia", "brain organic psychosis", "neurosis", "mood disorder", "dissociative disorder"]
}.each do |category, conditions|
  conditions.each do |condition|
    Condition.where(category: category, name: condition).first_or_create
    printf '.'
  end
end

puts ''
