puts "Create symptoms "

{
'Common symptoms of respiratory system' => ["Breathlessness", "Cough", "Sputum", "Blood in sputum(hemoptysis)", "Wheezing", "Pain in chest", "fever", "fatigue", "chest tightness", "nasal congestion", "runny nose", "Headache ", "Ear pain", "Toothache (dental pain)", "Facial fullness or congestion", "Decreased sense of smell", "General muscle aches and pains", "Lack of appetite", "Ankle swelling from fluid retention", "Heart pain (Angina)"],
'Common symptoms of the circulatory system(cardiovascular system)' => ["Fatigue", "Constant dizziness or lightheadedness", "Fast heart rate ", "Chest pain or discomfort ", "Breathlessness", "A respiratory infection or cough that becomes worse", "Restlessness or confusion", "Changes in sleep patterns", "Heart beat less than 60 beats per minute", "Nausea/vomiting", "Loss of appetite or heartburn", "Tiredness or weakness", "Coughing", "Heart flutters or palpitations", "Discomfort spreading or radiating to  back, jaw, throat, or arm", "Weakness, anxiety, or shortness of breath", "Rapid or irregular heartbeats", "edema", "Lump or bulge"],
'Common symptoms of the digestive system' => ["Abdominal pain", "Constipation", "Diarrhea", "Gas in the GI tract", "GI bleeding", "Nausea ", "Vomiting", "Heartburn/reflux", "bloating", "A change in normal bowel habits", "Blood on or in the stool ", "Narrowing of stool", "Unexplained weight loss", "Fatigue", " rectal bleeding", " constant tiredness.", " intense burning pain, bleeding, or spasm after bowel movements.", "Abdominal cramps", "Distended stomach"],
'Common symptoms of the urinary system' => ["Frequent and urgent need to urinate", "Passing only small amounts of urine", "Pain in the abdomen or pelvic area, or in the low back", "Burning sensation during urination", "Leaking urine", "Increased need to get up at night to urinate", "Cloudy, bad-smelling urine", "Blood in the urine", "Low-grade fever", "Fatigue", "Difficulty starting to urinate", "Weak urination stream", "Dribbling at end of urination", "Sensation of incomplete bladder emptying", "Pain during and after intercourse or during orgasms"],
'Common symptoms of the blood system' => ["fever", "Pneumonia", "Ulcers in the mouth", "Bleeding gums", "weakness", "Swollen tonsills", "Fatigue", "Weight loss", "Enlarged liver", "Enlarged spleen", "Shortness of breath", "Dizziness", "Headache", "Coldness in the hands and feet", "Chest pain", "Rapid or irregular heartbeat", "Easy bruising", "Frequent infections", "Nosebleed ", "Fever", "Dark brown urine", "Jaundice (yellow skin)", "Pallor (pale skin)", "Muscle pains", "Nausea and vomiting", "Diarrhea", "Painless swelling in the neck, underarms, stomach, or groin", "Tiredness", "Unexplained weight loss", "Reduced exercise tolerance", "Abdominal pain", "Loss of sex drive", "Heart problems", "Bleeding into muscles", "Bleeding into the intestinal tract", "Difficulty stopping bleeding after minor cuts or bumps", "Fingernail changes", "Heart palpitations", "Hair loss", "Bone or joint pain"],
'Common symptoms of the endocrine system' => ["Abnormally large growth and deformity of hands, face,feet,jaws,lips and tongue", "Thickened, oily skin", "Severe Acne", "Excessive sweating ", "Deepening voice", "Fatigue and weakness", "Sleep Apnea", "Arthritis and other joint problems", "High Blood Pressure", "Impotence ", "Weight loss", "Nausea or vomiting", "Diarrhea", "Muscle weakness", "Emotional changes, especially Depression", "Abdominal pain", "Headache", "Loss of vision", "Weight gain ", "Purple stretch marks", "Easy bruising", "Excess hair growth or acne in women", "Menstrual disorders, especially infrequent or absent periods", "Water retention or swelling", "Osteoporosis or brittle bones", "Increased thirst", "Low back pain", "Fever", "Blurred vision", "Low blood pressure", "Frequent urination", "Dehydration", "Constipation", "Loss of appetite", "Back pain", "Heat intolerance", "Heart palpitations, irregular heartbeat, skipped beats", "rapid heartbeat and pulse", "Increased bowel movements", "Insomnia", "Tremor", "Loss of libido", "Bulging eyes (called exophthalmos)", "Shortness of breath", "Swelling in legs", "Weakness", "Muscle cramps or twitching", "Loss of memory", "Thin, brittle nails", "Poor overall growth", "Short stature", "Small heart", "Sensitivity to cold", "Constipation", "Brittle and coarse Hairs", "Vaginal dryness", "Loss of some gender-specific sexual characteristics (women may lose hair from their underarms, body, and pubic area)", "Small testes", "Breast enlargement in men", "goiter ", "Swollen feet or hands", "Infertility", "Reduced sweating", "Sleep Apnea", "Diffuse swelling of the skin and tissue around the eyes", "Hypothermia (low body temperature)", "Fruity breath odor", "Slow wound healing", "Diabetic Foot Ulcer"],
'Common symptoms of the nervous system' => ["Agitation", "Anxiety", "apathy", "Fainting", "Tightness in head and neck muscles", "Difficulty concentrating", "First felt soon after waking", "Insomnia", "Grinding teeth", "Progressive weakening of muscles", "Enlargement of muscles as they weaken", "Clumsiness", "Frequent falling and difficulty getting up", "coma", "compulsive behaviour", "confusion", "depression", "Disorientation", "dizziness", "drowsiness", "emotional detachment", "fever", "hallucinations", "headache", "impaired vision", "blurred vision", "impaired judgement", "lump or bulge", "seizure", "tenderness"],
'Common symptoms of genital system' => ["Vaginal dryness", "Vaginal itching or burning", "Vaginal pain", "Painful intercourse", "Bleeding between your regular menstrual periods", "Menstrual bleeding that is heavier or lasts longer than usual", "Bleeding after sexual intercourse", "Increased vaginal discharge", "Pain during sexual intercourse ", "Infertility", "Pain in the testes", "Redness or swelling of the scrotum", "Hardness, a lump, and/or soreness in testicle", "Chills", "Fever", "Pain and/or burning during urination", "Increased pain while having a bowel movement", "Discharge from the penis", "Blood in the semen", "Enlarged or twisted vein in the scrotum", "A less firm penis", "Fewer erections", "Unexplained weight gain or loss", "Loss of force of the stream of urine", "Impotence"],
'Common symptoms of the locomotor system' => ["Pain", "Joint movement disorder", "trauma", "fracture", "Pain, particularly with activity", "Decreased motion of related joints", "Local swelling", "Pain in the joint", "Popping, clicking, or grating sounds or sensations while using the joint", "Difficulty in functioning of the joint", "Muscle pain/spasm in the ar“ea of the  joint", "localised Swelling"],
'Common symptoms metabolic and nutrition conditions' => ["Overweight", "Skeletal and/or skull deformities", "Bow legs or knock knees", "Deformity or curvature of the spine", "Pigeon chest (forward protrusion of the chest bone)", "Impaired growth, resulting in short stature", "Susceptibility to bone fractures", "Dental deformities", "Defects in teeth", "Difficulty sleeping", "Poor muscle development and tone", "Delay of learning to walk in children", "Sunken eyes", "Reopening of old wounds or sores", "Internal bleeding", "Bruising easily", "Weight loss", "Diarrhea", "Irritability", "Aching and swelling in joints", "Shortness of breath", "Fatigue", "Sensation of pins and needles in feet or hands", "Stinging sensation on the tongue or smooth red tongue", "Substantial weight loss", "Inability to distinguish the colors yellow and blue", "Tiredness", "Paleness", "Loss of hunger", "Altered sense of taste", "Confusion", "Depression", "Impaired sense of balance, especially in the dark", "Tinnitus", "Cracked lips", "Yellow skin", "Fever", "Inability to sense vibrations in feet or legs", "Dizziness when changing to standing position", "Rapid heart rate", "Diffuse bone and muscle pain", "Muscle weakness", "Fracture"],
'Dental & Oral Diseases' => ["Pain in the gums", "Bad taste in mouth, extremely bad breath", "Red and swollen gums", "Fever", "Swollen lymph nodes", "Tendency for gums to bleed, particularly with tooth brushing and flossing", "Persistent bad breath (halitosis)", "Pain during chewing", "Loose teeth", "Shrunken, receding gum line", "Pockets or gaps between the teeth and the gums", "Pus oozing from the gums or between the teeth", "Tooth sensitivity to hot or cold", "Tooth discomfort after eating", "Darkening of the tooth surface", "Throbbing, lingering pain in tooth"]
  }.each do |category, symptoms|
  symptoms.each do |symptom|
    Symptom.where(category: category, name: symptom).first_or_create
    printf '.'
  end
end

puts ''
