# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'ReactiveCocoa'
pod 'RealmSwift'
pod 'XMPPFramework'
pod 'AFNetworking', '~> 2.6'
pod 'AFOAuth2Manager', :git => 'https://github.com/AFNetworking/AFOAuth2Manager.git'