# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

pod 'PureLayout'
pod 'Masonry'
pod 'MagicalRecord'
pod 'ReactiveCocoa', '4.0.4-alpha-1'
pod 'AFNetworking', '~> 3.0.0-beta.1'

