# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

pod 'PureLayout'
pod 'Masonry'
pod 'MagicalRecord'
pod 'AFNetworking', '~> 3.0.0-beta.1'
pod 'DACircularProgress'
pod 'MBProgressHUD'
pod 'SDWebImage'
pod 'pop'
pod 'YYKit'