source 'http://rubygems.org'

gem 'rails', '~> 4.1.0'

gem 'pg'
gem 'warden'
gem 'grape'
gem "simple_form", "~> 3.0.2"
gem 'remotipart', '~> 1.2'
gem 'country_select'
gem 'haml-rails'
gem 'chosen-rails'
gem 'oily_png'
gem 'kaminari'
gem 'mini_magick'
gem 'carrierwave'
gem 'carrierwave_backgrounder'
gem 'resque-scheduler', :require => 'resque-scheduler'
gem 'resque-web', require: 'resque_web'
gem 'httparty'
gem 'exception_notification'
gem 'bcrypt-ruby', '~> 3.1.2'
gem 'grape-swagger'
gem 'grape-swagger-ui'
gem 'redis-rails'
gem 'retina_tag'
gem 'font-awesome-sass'
gem 'apn_sender', git: 'https://github.com/arthurnn/apn_sender'
gem 'draper' # Presenter
gem 'oj'     # Faster json handling
gem 'twitter'
gem "geocoder"
gem 'rails-observers'
gem 'globalize', '~> 4.0.3'

gem 'sass-rails', '~> 4.0.0'
gem 'sprockets', '2.11.0' # 2.12.0 is broken

gem 'uglifier', '>= 1.3.0'
# gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'jquery-ui-rails'
gem 'select2-rails'
gem 'fancybox2-rails', '~> 0.2.4'
gem 'turbolinks'
gem 'jquery-turbolinks'
# gem 'therubyracer', platforms: :ruby
gem 'jbuilder'
gem 'roo', require: false
gem 'thin', require: false
gem 'unicorn', require: false

gem "ffaker", "~> 1.20.0"
gem "random_data", "~> 1.6.0"

gem 'newrelic_rpm'
gem "google-api-client"

gem 'rseg', github: "SaitoWu/rseg"
gem 'chinese_pinyin'

gem 'mailboxer'

gem 'rqrcode-with-patches', require: ['rqrcode', 'rqrcode/export/png']

# gem 'rubysl', require: false, platforms: :rbx
group :development do
  gem 'better_errors'
  gem 'capistrano-db-tasks', '0.2.1', require: false
end

group :doc do
  gem 'sdoc', require: false
end

group :development, :test do
  gem 'spring'
  gem 'pry'
  gem 'pry-rails'
  gem 'capistrano'
  gem 'rvm-capistrano', require: false
  gem 'capistrano-unicorn', require: false
  gem 'quiet_assets'
  gem 'brakeman', '~> 1.3', require: false
  gem 'puma', require: false, platforms: [:rbx, :jruby]
  gem 'mail_view'
  gem 'binding_of_caller'
  gem 'i18n-tasks', '~> 0.7.6'
  gem 'guard'
  gem 'guard-rspec', require: false
  gem 'guard-cucumber', require: false
  gem 'guard-livereload', require: false
  gem 'guard-rails', require: false
  gem 'spring-commands-rspec'
  gem 'spring-commands-cucumber'
  gem 'railroady'
  gem 'awesome_print', require: 'ap'
  gem 'typhoeus'
end

group :test do
  gem 'cucumber-rails', require: false
  gem 'cucumber-api-steps', require: false
  gem 'database_cleaner'
  gem 'rspec-rails'
  gem "factory_girl_rails", "~> 4.4.1"
  gem 'rails-perftest'
  gem 'ruby-prof'
  gem 'simplecov', require: false
  gem 'timecop'
end
